package com.personaledge.core.agent

import com.personaledge.core.tools.ToolDescriptor
import com.personaledge.core.tools.ToolRisk
import java.security.MessageDigest
import java.util.Collections
import java.util.LinkedHashSet
import java.util.Locale
import java.util.PriorityQueue
import java.util.UUID

/** Opaque UUID generated by Kotlin. It cannot carry prompt or model-argument text. */
@ConsistentCopyVisibility
data class AgentPlanId private constructor(val value: String) {
    companion object {
        fun parse(value: String): AgentPlanId? = runCatching { UUID.fromString(value) }
            .getOrNull()
            ?.takeIf { parsed -> parsed.toString() == value }
            ?.let { AgentPlanId(value) }

        fun random(): AgentPlanId = AgentPlanId(UUID.randomUUID().toString())
    }
}

/** Small numeric identity so a model cannot smuggle content into a persisted step label. */
@JvmInline
value class AgentPlanStepId(val value: Int) : Comparable<AgentPlanStepId> {
    init {
        require(value in 1..MAX_VALUE)
    }

    override fun compareTo(other: AgentPlanStepId): Int = value.compareTo(other.value)

    companion object {
        const val MAX_VALUE = 10_000
    }
}

/** SHA-256 value used to bind content without retaining the content itself. */
@ConsistentCopyVisibility
data class AgentPlanDigest private constructor(val hex: String) {
    companion object {
        fun parse(value: String): AgentPlanDigest? = value
            .takeIf(SHA256::matches)
            ?.let(::AgentPlanDigest)

        internal fun sha256(value: String): AgentPlanDigest = AgentPlanDigest(
            MessageDigest.getInstance("SHA-256")
                .digest(value.toByteArray(Charsets.UTF_8))
                .joinToString("") { byte -> "%02x".format(Locale.ROOT, byte) },
        )

        private val SHA256 = Regex("[0-9a-f]{64}")
    }
}

/** Tool names become persistable only after matching an app-owned policy catalog. */
@ConsistentCopyVisibility
data class AgentPlanToolName private constructor(val value: String) : Comparable<AgentPlanToolName> {
    override fun compareTo(other: AgentPlanToolName): Int = value.compareTo(other.value)

    companion object {
        fun parse(value: String): AgentPlanToolName? = value
            .takeIf { candidate -> candidate.length <= MAX_CHARACTERS && TOOL_NAME.matches(candidate) }
            ?.let(::AgentPlanToolName)

        private const val MAX_CHARACTERS = 64
        private val TOOL_NAME = Regex("[a-z][a-z0-9_]*")
    }
}

/** Closed resource classes. Concrete resource identifiers are represented only by a digest. */
enum class AgentPlanResourceKind {
    CALENDAR,
    ALARM,
    REMINDER,
    NOTIFICATION,
    NETWORK,
    MEMORY,
    PROPOSAL,
    COMMUNICATION_TARGET,
    APP_STATE,
}

data class AgentPlanResource(
    val kind: AgentPlanResourceKind,
    val scopeDigest: AgentPlanDigest,
)

/** Model-declared risk. [PlanVerifier] replaces it with the trusted catalog value. */
enum class AgentPlanRisk {
    READ_ONLY,
    LOCAL_WRITE,
    DATA_WRITE,
    COMMUNICATION,
    VEHICLE_CONTROL,
    HIGH_RISK,
    ;

    companion object {
        fun fromToolRisk(risk: ToolRisk): AgentPlanRisk = when (risk) {
            ToolRisk.READ_ONLY -> READ_ONLY
            ToolRisk.LOCAL_WRITE -> LOCAL_WRITE
            ToolRisk.DATA_WRITE -> DATA_WRITE
            ToolRisk.COMMUNICATION -> COMMUNICATION
            ToolRisk.VEHICLE_CONTROL -> VEHICLE_CONTROL
            ToolRisk.HIGH_RISK -> HIGH_RISK
        }
    }
}

/**
 * Non-executable model proposal.
 *
 * It contains no canonical arguments, execution permit, callback, or Tool instance. Ephemeral
 * arguments remain outside this kernel and can later be rebound only after their digest matches.
 */
data class AgentPlanStep(
    val id: AgentPlanStepId,
    val toolName: AgentPlanToolName,
    val argumentDigest: AgentPlanDigest,
    val dependsOn: Set<AgentPlanStepId> = emptySet(),
    val readSet: Set<AgentPlanResource> = emptySet(),
    val writeSet: Set<AgentPlanResource> = emptySet(),
    val declaredRisk: AgentPlanRisk,
)

/** The objective is represented only by a digest; raw prompt text never enters a checkpoint. */
data class AgentPlan(
    val id: AgentPlanId,
    val objectiveDigest: AgentPlanDigest,
    val expiresAtEpochMillis: Long,
    val steps: List<AgentPlanStep>,
)

/** App-owned metadata derived from shipped Tool descriptors, never from model output. */
@ConsistentCopyVisibility
data class TrustedAgentPlanToolPolicy private constructor(
    val toolName: AgentPlanToolName,
    val risk: AgentPlanRisk,
    val readableResourceKinds: Set<AgentPlanResourceKind>,
    val writableResourceKinds: Set<AgentPlanResourceKind>,
) {
    init {
        require(risk != AgentPlanRisk.READ_ONLY || writableResourceKinds.isEmpty())
    }

    companion object {
        fun create(
            toolName: AgentPlanToolName,
            risk: AgentPlanRisk,
            readableResourceKinds: Set<AgentPlanResourceKind> = emptySet(),
            writableResourceKinds: Set<AgentPlanResourceKind> = emptySet(),
        ): TrustedAgentPlanToolPolicy = TrustedAgentPlanToolPolicy(
            toolName = toolName,
            risk = risk,
            readableResourceKinds = Collections.unmodifiableSet(
                LinkedHashSet(readableResourceKinds),
            ),
            writableResourceKinds = Collections.unmodifiableSet(
                LinkedHashSet(writableResourceKinds),
            ),
        )

        fun fromDescriptor(
            descriptor: ToolDescriptor,
            readableResourceKinds: Set<AgentPlanResourceKind> = emptySet(),
            writableResourceKinds: Set<AgentPlanResourceKind> = emptySet(),
        ): TrustedAgentPlanToolPolicy? = AgentPlanToolName.parse(descriptor.name)?.let { name ->
            create(
                toolName = name,
                risk = AgentPlanRisk.fromToolRisk(descriptor.risk),
                readableResourceKinds = readableResourceKinds,
                writableResourceKinds = writableResourceKinds,
            )
        }
    }
}

class AgentPlanPolicyCatalog private constructor(
    private val policies: Map<AgentPlanToolName, TrustedAgentPlanToolPolicy>,
) {
    internal fun policyFor(name: AgentPlanToolName): TrustedAgentPlanToolPolicy? = policies[name]

    companion object {
        fun create(policies: List<TrustedAgentPlanToolPolicy>): AgentPlanPolicyCatalog {
            require(policies.isNotEmpty())
            val byName = policies.associateBy(TrustedAgentPlanToolPolicy::toolName)
            require(byName.size == policies.size) { "Plan tool policies must have unique names." }
            return AgentPlanPolicyCatalog(Collections.unmodifiableMap(LinkedHashMap(byName)))
        }
    }
}

data class PlanVerifierLimits(
    val maxSteps: Int = 8,
    val maxDependenciesPerStep: Int = 8,
    val maxResourcesPerStep: Int = 16,
    val maxLifetimeMillis: Long = 5 * 60_000L,
) {
    init {
        require(maxSteps in 1..32)
        require(maxDependenciesPerStep in 0..32)
        require(maxResourcesPerStep in 0..64)
        require(maxLifetimeMillis in 1_000L..30 * 60_000L)
    }
}

enum class PlanViolationCode {
    EMPTY_PLAN,
    TOO_MANY_STEPS,
    EXPIRED,
    LIFETIME_TOO_LONG,
    DUPLICATE_STEP_ID,
    TOO_MANY_DEPENDENCIES,
    UNKNOWN_DEPENDENCY,
    SELF_DEPENDENCY,
    DEPENDENCY_CYCLE,
    UNKNOWN_TOOL,
    RISK_MISMATCH,
    TOO_MANY_RESOURCES,
    READ_ONLY_WRITE_SET,
    READ_RESOURCE_NOT_ALLOWED,
    WRITE_RESOURCE_NOT_ALLOWED,
}

/** Closed violation metadata; no model name, argument, prompt, or resource value is echoed. */
data class PlanViolation(
    val code: PlanViolationCode,
    val stepId: AgentPlanStepId? = null,
)

sealed interface PlanVerificationResult {
    data class Accepted(val plan: VerifiedAgentPlan) : PlanVerificationResult

    data class Rejected(val violations: List<PlanViolation>) : PlanVerificationResult {
        init {
            require(violations.isNotEmpty())
        }
    }
}

/** A verifier-issued step. Its trusted risk cannot be supplied by the model. */
@ConsistentCopyVisibility
data class VerifiedAgentPlanStep internal constructor(
    val id: AgentPlanStepId,
    val toolName: AgentPlanToolName,
    val argumentDigest: AgentPlanDigest,
    val dependsOn: Set<AgentPlanStepId>,
    val readSet: Set<AgentPlanResource>,
    val writeSet: Set<AgentPlanResource>,
    val risk: AgentPlanRisk,
)

/** Capability token for the MVP executor; only [PlanVerifier] can construct it. */
class VerifiedAgentPlan internal constructor(
    val id: AgentPlanId,
    val expiresAtEpochMillis: Long,
    val planDigest: AgentPlanDigest,
    steps: List<VerifiedAgentPlanStep>,
) {
    val steps: List<VerifiedAgentPlanStep> = Collections.unmodifiableList(steps.toList())
}

/**
 * Deterministic structural and policy verifier.
 *
 * Verification does not prepare or execute a Tool. Existing strict parsing, ToolOrchestrator,
 * confirmation, interlock, and ledger boundaries remain the only future execution route.
 */
class PlanVerifier(
    private val catalog: AgentPlanPolicyCatalog,
    private val limits: PlanVerifierLimits = PlanVerifierLimits(),
    private val clock: () -> Long = System::currentTimeMillis,
) {
    fun verify(proposal: AgentPlan): PlanVerificationResult {
        val now = clock()
        val violations = mutableListOf<PlanViolation>()
        if (proposal.steps.isEmpty()) {
            return PlanVerificationResult.Rejected(
                listOf(PlanViolation(PlanViolationCode.EMPTY_PLAN)),
            )
        }
        if (proposal.steps.size > limits.maxSteps) {
            return PlanVerificationResult.Rejected(
                listOf(PlanViolation(PlanViolationCode.TOO_MANY_STEPS)),
            )
        }
        if (proposal.expiresAtEpochMillis <= now) {
            violations += PlanViolation(PlanViolationCode.EXPIRED)
        } else if (proposal.expiresAtEpochMillis > saturatedAdd(now, limits.maxLifetimeMillis)) {
            violations += PlanViolation(PlanViolationCode.LIFETIME_TOO_LONG)
        }

        val sortedSteps = proposal.steps.sortedBy(AgentPlanStep::id)
        sortedSteps.forEach { step ->
            if (step.dependsOn.size > limits.maxDependenciesPerStep) {
                violations += PlanViolation(PlanViolationCode.TOO_MANY_DEPENDENCIES, step.id)
            }
            if (step.readSet.size.toLong() + step.writeSet.size.toLong() >
                limits.maxResourcesPerStep.toLong()
            ) {
                violations += PlanViolation(PlanViolationCode.TOO_MANY_RESOURCES, step.id)
            }
        }
        if (violations.any { violation ->
                violation.code == PlanViolationCode.TOO_MANY_DEPENDENCIES ||
                    violation.code == PlanViolationCode.TOO_MANY_RESOURCES
            }
        ) {
            return PlanVerificationResult.Rejected(violations.toList())
        }

        val stepIds = sortedSteps.map(AgentPlanStep::id)
        val duplicateIds = stepIds.groupingBy { id -> id }.eachCount()
            .filterValues { count -> count > 1 }
            .keys
            .sorted()
        duplicateIds.forEach { id ->
            violations += PlanViolation(PlanViolationCode.DUPLICATE_STEP_ID, id)
        }
        val knownIds = stepIds.toSet()

        sortedSteps.forEach { step ->
            if (step.id in step.dependsOn) {
                violations += PlanViolation(PlanViolationCode.SELF_DEPENDENCY, step.id)
            }
            if (step.dependsOn.any { dependency -> dependency !in knownIds }) {
                violations += PlanViolation(PlanViolationCode.UNKNOWN_DEPENDENCY, step.id)
            }
            val policy = catalog.policyFor(step.toolName)
            if (policy == null) {
                violations += PlanViolation(PlanViolationCode.UNKNOWN_TOOL, step.id)
                return@forEach
            }
            if (step.declaredRisk != policy.risk) {
                violations += PlanViolation(PlanViolationCode.RISK_MISMATCH, step.id)
            }
            if (policy.risk == AgentPlanRisk.READ_ONLY && step.writeSet.isNotEmpty()) {
                violations += PlanViolation(PlanViolationCode.READ_ONLY_WRITE_SET, step.id)
            }
            if (step.readSet.any { resource -> resource.kind !in policy.readableResourceKinds }) {
                violations += PlanViolation(PlanViolationCode.READ_RESOURCE_NOT_ALLOWED, step.id)
            }
            if (policy.risk != AgentPlanRisk.READ_ONLY &&
                step.writeSet.any { resource -> resource.kind !in policy.writableResourceKinds }
            ) {
                violations += PlanViolation(PlanViolationCode.WRITE_RESOURCE_NOT_ALLOWED, step.id)
            }
        }

        val hasInvalidDependency = violations.any { violation ->
            violation.code == PlanViolationCode.UNKNOWN_DEPENDENCY ||
                violation.code == PlanViolationCode.SELF_DEPENDENCY
        }
        if (duplicateIds.isEmpty() && !hasInvalidDependency) {
            cyclicStepIds(proposal.steps).forEach { id ->
                violations += PlanViolation(PlanViolationCode.DEPENDENCY_CYCLE, id)
            }
        }
        if (violations.isNotEmpty()) return PlanVerificationResult.Rejected(violations.toList())

        val verifiedSteps = sortedSteps
            .map { step ->
                val policy = checkNotNull(catalog.policyFor(step.toolName))
                VerifiedAgentPlanStep(
                    id = step.id,
                    toolName = policy.toolName,
                    argumentDigest = step.argumentDigest,
                    dependsOn = immutableSet(step.dependsOn),
                    readSet = immutableSet(step.readSet),
                    writeSet = immutableSet(step.writeSet),
                    risk = policy.risk,
                )
            }
        return PlanVerificationResult.Accepted(
            VerifiedAgentPlan(
                id = proposal.id,
                expiresAtEpochMillis = proposal.expiresAtEpochMillis,
                planDigest = digestOf(proposal, verifiedSteps),
                steps = verifiedSteps,
            ),
        )
    }

    private fun cyclicStepIds(steps: List<AgentPlanStep>): List<AgentPlanStepId> {
        if (steps.isEmpty()) return emptyList()
        val indegree = steps.associate { step -> step.id to step.dependsOn.size }.toMutableMap()
        val dependents = mutableMapOf<AgentPlanStepId, MutableList<AgentPlanStepId>>()
        steps.forEach { step ->
            step.dependsOn.forEach { dependency ->
                dependents.getOrPut(dependency, ::mutableListOf).add(step.id)
            }
        }
        val ready = PriorityQueue<AgentPlanStepId>()
        indegree.filterValues { count -> count == 0 }.keys.forEach(ready::add)
        var visited = 0
        while (ready.isNotEmpty()) {
            val id = ready.remove()
            visited++
            dependents[id].orEmpty().sorted().forEach { dependent ->
                val next = checkNotNull(indegree[dependent]) - 1
                indegree[dependent] = next
                if (next == 0) ready.add(dependent)
            }
        }
        return if (visited == steps.size) emptyList() else {
            indegree.filterValues { count -> count > 0 }.keys.sorted()
        }
    }

    private fun digestOf(
        proposal: AgentPlan,
        steps: List<VerifiedAgentPlanStep>,
    ): AgentPlanDigest = AgentPlanDigest.sha256(
        buildString {
            append("agent-plan-v1\n")
            append(proposal.id.value).append('\n')
            append(proposal.objectiveDigest.hex).append('\n')
            append(proposal.expiresAtEpochMillis).append('\n')
            steps.forEach { step ->
                append(step.id.value).append('|')
                append(step.toolName.value).append('|')
                append(step.risk.name).append('|')
                append(step.argumentDigest.hex).append('|')
                step.dependsOn.sorted().forEach { dependency -> append(dependency.value).append(',') }
                append('|')
                step.readSet.sortedBy { resource -> resource.canonicalKey() }
                    .forEach { resource -> append(resource.canonicalKey()).append(',') }
                append('|')
                step.writeSet.sortedBy { resource -> resource.canonicalKey() }
                    .forEach { resource -> append(resource.canonicalKey()).append(',') }
                append('\n')
            }
        },
    )

    private fun AgentPlanResource.canonicalKey(): String = "${kind.name}:${scopeDigest.hex}"

    private fun <T> immutableSet(values: Set<T>): Set<T> =
        Collections.unmodifiableSet(LinkedHashSet(values))

    private fun saturatedAdd(first: Long, second: Long): Long =
        if (Long.MAX_VALUE - first < second) Long.MAX_VALUE else first + second
}
